apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
  annotations:
    werf.io/weight: "-40"
spec:
  selector:
    app.kubernetes.io/name: keycloak
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 90
      targetPort: management
      name: management
