apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app.kubernetes.io/name: kafdrop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kafdrop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:4.0.2
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
            - name: KAFKA_BROKERCONNECT
              value: "kafka-kafka-bootstrap:9092"
