apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    app.kubernetes.io/name: kafdrop
  annotations:
    werf.io/weight: "-20"
spec:
  selector:
    app.kubernetes.io/name: kafdrop
  ports:
    - port: 9000
      name: http
      targetPort: http
