apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
  annotations:
    werf.io/weight: "-10"
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - port: 80
      name: http
      targetPort: http
