apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app.kubernetes.io/name: reservation
  annotations:
    werf.io/weight: "-10"
spec:
  selector:
    app.kubernetes.io/name: reservation
  ports:
    - port: 80
      name: http
      targetPort: http
