spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: backend
    password: backend
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
