apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: gateway
        image: {{ .Values.werf.image.gateway }}
        env:
          - name: app.debug-mode
            value: "{{ .Values.gateway.debug }}"
          - name: app.interop.reservation-client-api
            value: http://reservation
          - name: app.interop.payment-client-api
            value: http://payment
          - name: app.interop.loyalty-client-api
            value: http://loyalty
          - name: app.interop.stats-client-api
            value: http://stats
          - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
            value: http://keycloak/auth/realms/rsoi-hotels/protocol/openid-connect/certs # try external if fails
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
            path: /api/gateway/manage/health
          periodSeconds: 5
          failureThreshold: 6
          initialDelaySeconds: 2
        readinessProbe:
          httpGet:
            port: http
            path: /api/gateway/manage/health
          periodSeconds: 5
          initialDelaySeconds: 2
        startupProbe:
          httpGet:
            port: http
            path: /api/gateway/manage/health
          periodSeconds: 2
          failureThreshold: 30
          initialDelaySeconds: 2
        resources:
          {{- toYaml .Values.gateway.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /workdir
            name: workdir
      volumes:
        - name: workdir
          emptyDir: {}
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
