apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
spec:
  replicas: {{ .Values.payment.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: payment
        image: {{ .Values.werf.image.payment }}
        env:
          - name: app.debug-mode
            value: "{{ .Values.payment.debug }}"
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 5
          failureThreshold: 6
          initialDelaySeconds: 2
        readinessProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 5
          initialDelaySeconds: 2
        startupProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 2
          failureThreshold: 30
          initialDelaySeconds: 2
        resources:
          {{- toYaml .Values.payment.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /workdir
            name: workdir
      volumes:
        - name: workdir
          emptyDir: {}
      {{- with .Values.payment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.payment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
