apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  labels:
    app.kubernetes.io/name: loyalty
  annotations:
    werf.io/weight: "-10"
spec:
  replicas: {{ .Values.loyalty.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: loyalty
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loyalty
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: loyalty
        image: {{ .Values.werf.image.loyalty }}
        env:
          - name: app.debug-mode
            value: "{{ .Values.loyalty.debug }}"
          - name: spring.datasource.url
            value: jdbc:postgresql://hoteldb-rw:5432/loyalty
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                key: user
                name: hoteldb-superuser
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                key: password
                name: hoteldb-superuser
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 5
          failureThreshold: 6
          initialDelaySeconds: 2
        readinessProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 5
          initialDelaySeconds: 2
        startupProbe:
          httpGet:
            port: http
            path: /manage/health
          periodSeconds: 2
          failureThreshold: 30
          initialDelaySeconds: 2
        resources:
          {{- toYaml .Values.loyalty.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /workdir
            name: workdir
      volumes:
        - name: workdir
          emptyDir: {}
      {{- with .Values.loyalty.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loyalty.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
