payment:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

loyalty:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

reservation:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

gateway:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []
