payment:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

loyalty:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

reservation:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

gateway:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

hoteldb:
  instances: 1
  storage:
    class: csi-rbd-sc
    size: 4Gi
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 4096Mi
  parameters:
    max_connections: "100"
    max_prepared_transactions: "100"
    superuser_reserved_connections: "10"

keycloakdb:
  instances: 1
  storage:
    class: csi-rbd-sc
    size: 2Gi
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 4096Mi
  parameters:
    max_connections: "100"
    max_prepared_transactions: "100"

secure: false

keycloak:
  enabled: true
  resources:
    requests:
      cpu: 1m
      memory: 376Mi
    limits:
      memory: 4Gi

frontend:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []

stats:
  enabled: true
  replicas: 1
  debug: true
  resources:
    requests:
      cpu: 2m
      memory: 455Mi
    limits:
      memory: 4Gi
  nodeSelector: {}
  tolerations: []
