name: Cleanup

on:
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger the workflow'
        required: true

jobs:
  recreate:
    name: Cleanup
    runs-on: arc-runner-set-2

    permissions:
      contents: read
      packages: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install git -y
          sudo apt install buildah -y

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2.320

      - name: Log in to registry
        run: echo "${{ secrets.SECRET_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run script
        run: |
          . $(werf ci-env github --as-file)
          export WERF_BUILDAH_MODE=auto
          werf cleanup --repo-github-token ${{ secrets.SECRET_TOKEN }}
